#+TITLE: dotfiles
* xorg
** xinitrc

I found an example configuration for the retina display at
https://ellipticaldoor.com/2017-10-11-installing-arch-linux-on-a-macbook-with-retina-hidpi-support-and-graphic-switching/
Currently I have commented out the gdk and qt settings until I read up on what
they actually does. The xrandr command however I needed because by default the
output of the ~xrandr -q~ said the dpi was 96 which was clearly incorrect. I
verified that the 227 was correct by consulting the apple website for the
macbook specs.

#+NAME: xinit-hidpi
#+BEGIN_SRC sh
#export GDK_SCALE=2
#export GDK_DPI_SCALE=0.95
#export QT_SCREEN_SCALE_FACTORS=0.9
#export QT_AUTO_SCREEN_SCALE_FACTOR=2
#export QT_SCALE_FACTOR=2

xrandr --dpi 227
#+END_SRC

I need to launch sxhkd since bspwm is relying upon that program to handle the
keybindings. I launch the terminal as well at startup. It can be convinent at
times when I hadn't installed rofi. Can probably be removed now.
#+NAME: xinit-programs
#+BEGIN_SRC sh
sxhkd &
urxvt &
exec bspwm
#+END_SRC

#+BEGIN_SRC text :tangle ~/.xinitrc :noweb yes
#! /bin/sh

# customize xresources
[[ -f ~/.Xresources ]] && xrdb  ~/.Xresources

# hidpi settings
<<xinit-hidpi>>

# start programs
<<xinit-programs>>
#+END_SRC

** xresources

The configuration of hidpi parameters originate from
https://ellipticaldoor.com/2017-10-11-installing-arch-linux-on-a-macbook-with-retina-hidpi-support-and-graphic-switching/
#+NAME: xresources-hidpi
#+BEGIN_SRC sh
!! hidpi
Xft.dpi: 227
Xft.rgba: rgb
Xft.antialias: true
Xft.hinting: false
Xft.lcdfilter: lcddefault
#+END_SRC

The colors originate from ~hlissners~ dotfiles setup. Another source for color
schemes might be https://terminal.sexy/.
#+NAME: xresources-colors
#+BEGIN_SRC sh
!! Colors
#define blk  #141517
#define bblk #969896
#define red  #cc6666
#define bred #de935f
#define grn  #b5bd68
#define bgrn #757d28
#define ylw  #f0c674
#define bylw #f9a03f
#define blu  #81a2be
#define bblu #2a8fed
#define mag  #b294bb
#define bmag #bc77a8
#define cyn  #8abeb7
#define bcyn #a3685a
#define wht  #c5c8c6
#define bwht #ffffff
#define bg blk
#define fg wht

,*.foreground:  fg
,*.background:  bg
,*.cursorColor: mag

,*.color0:  blk
,*.color8:  bblk
,*.color1:  red
,*.color9:  bred
,*.color2:  grn
,*.color10: bgrn
,*.color3:  ylw
,*.color11: bylw
,*.color4:  blu
,*.color12: bblu
,*.color5:  mag
,*.color13: bmag
,*.color6:  cyn
,*.color14: bcyn
,*.color7:  wht
,*.color15: bwht

! greys
,*.color234: #1d2021
,*.color235: #282828
,*.color236: #32302f
,*.color237: #3c3836
,*.color239: #504945
,*.color240: #544c49
,*.color241: #665c54

!! cursor
Xcursor.theme: default
Xcursor.size: 32
#+END_SRC

The configuration of urxvt originates from ~hlissners~ setup as well.
#+NAME: xresources-urxvt
#+BEGIN_SRC sh
!! urxvt
URxvt*.background:             [96]blk
URxvt*.termName:               xterm-256color
URxvt*.geometry:               81x20
URxvt*.buffered:               true
URxvt*.cursorBlink:            true
URxvt*.underlineColor:         grey
URxvt*.depth:                  32
URxvt*.borderless:             1
URxvt.iso14755:                false
URxvt.iso14755_52:             false
URxvt*.internalBorder:         14
URxvt*.scrollBar:              false
URxvt*.saveLines:              5000
URxvt*.loginShell:             false
URxvt*.matcher.button:         1
URxvt*.matcher.rend.0:         Uline Bold fg5
URxvt*.url-launcher:           firefox

URxvt*.lineSpace:              0
URxvt*.letterSpace:            0
URxvt.font: xft:Iosevka Term:style=regular:size=8
URxvt.boldFont: xft:Iosevka Term:style=bold:size=8
#+END_SRC

#+BEGIN_SRC text :tangle ~/.Xresources :noweb yes
<<xresources-hidpi>>

<<xresources-colors>>

<<xresources-urxvt>>
#+END_SRC
